trigger:
- prod-ci

pool:
  name: Default

variables:
  - group: aws_credentials
  - group: github_token

stages:

# =====================================================
# CD STAGE
# =====================================================
- stage: CD
  displayName: "Deploy Model"

  jobs:
  - job: deploy
    displayName: "Deploy Latest Model"
    steps:

    # -----------------------------------
    # Deploy Latest Model from S3
    # -----------------------------------
    - script: |
        echo "Deploying latest model from S3..."

        git clone https://$(GITHUB_TOKEN)@github.com/amuthakrishna/End_to_End_greeting_mlops_CD.git -b prod-cd
        cd End_to_End_greeting_mlops_CD

        # -----------------------------------
        # STEP 1: Get latest model from S3
        # -----------------------------------
        LATEST_MODEL=$(aws s3 ls s3://greeting-model-s3/models/ \
            | sort | tail -n 1 | awk '{print $4}')

        echo "Latest model from S3: $LATEST_MODEL"

        aws s3 cp s3://greeting-model-s3/models/$LATEST_MODEL ./k8s/

        # -----------------------------------
        # STEP 2: Clean old models in repo
        # -----------------------------------
        rm -f k8s/intent_model_*.pkl

        mv k8s/$LATEST_MODEL k8s/intent_model.pkl

        echo "Model renamed to stable name: intent_model.pkl"

        # -----------------------------------
        # STEP 3: Extract version
        # -----------------------------------
        MODEL_VERSION=$(echo $LATEST_MODEL | cut -d'_' -f3-4 | cut -d'.' -f1)

        echo "Model Version: $MODEL_VERSION"

        # -----------------------------------
        # STEP 4: Update Kubernetes YAML
        # -----------------------------------
        sed -i "s/REPLACE_MODEL_VERSION/$MODEL_VERSION/g" k8s/inference.yaml

        echo "Updated inference.yaml"
        cat k8s/inference.yaml

        # -----------------------------------
        # STEP 5: Commit & Push
        # -----------------------------------
        git config user.email "amuthakrishna1988@gmail.com"
        git config user.name "amuthakrishna"

        git add k8s/intent_model.pkl k8s/inference.yaml
        git commit -m "Deploy latest model $MODEL_VERSION" || echo "No changes"
        git push

      displayName: "Deploy Latest Model from S3"